bot-token:
server-id:
timezone: Asia/Seoul
icon-storage:
  use: true
  url: https://api.mineatar.io/face/%s
status-updater:
  use: false
broadcaster:
  use: false
  channels: []
simple-forwarder:
  use: false
  message-type: webhook
  channels: []
translator-forwarder:
  use: false
  message-type: webhook
  channels: []
  languages:
    - en_US
    - ko_KR
channel-forwarder:
  use: false
  message-type: webhook
  prefix: '#'
  format: '§r%1$s <%%1$s> %%2$s'
  channels:
    - discordChannelId shortName
  default-listening-channels:
    - shortName
  default-speaking-channels:
    - shortName
group-linker:
  use: false
  context-key: discord:role
building-storage:
  use: false
  show-hologram: true
  api-endpoint:
  category-name:
  wiki-url:
  register-preload:
building-votes:
  use: false
builder-level:
  use: false
  require-role: discordRoleName
  broadcast-channels:
    - discordChannelId
  title-context-key: builder:title
builder-level-rewards:
  use: false
  attendance:
    use: false
    rewards: [10, 12, 14, 16, 18, 20, 30]
  chat:
    use: false
    messages: 20
    reward: 10
    max-reward: 30
  vote:
    use: false
    reward: 5