name: KubeCityBot
version: @version@
main: kr.kubecity.bot.KubeCityBotPlugin
author: Lee0701
authors: [Lee0701]
softdepend: [LuckPerms, RatTranslate, FancyHolograms]
description: Plugin for KubeCity.
commands:
  kubecitybot:
    aliases: [kubecitybot, kubebot, kcb, kb]
    description: "KubeCityBot main command."
  discord:
    description: "Discord link command."
