name: KubeCityBot
version: @version@
main: kr.kubecity.bot.KubeCityBotPlugin
author: Lee0701
authors: [Lee0701]
softdepend: [LuckPerms, RatTranslate, FancyHolograms]
description: Plugin for KubeCity.
commands:
  kubecitybot:
    aliases: [kubecitybot, kubebot, kcb, kb]
    description: "KubeCityBot main command."
  discord:
    description: "Discord link command."
  building:
    description: "Building command."
  level:
    description: "Builder level command."
permissions:
  kubecitybot.admin:
    description: Gives admin rights for KubeCityBot
    default: op
  kubecitybot.building.vote:
    description: Allows /building vote command
    default: true
  kubecitybot.building.register:
    description: Allows /building register command
    default: true
